#!/usr/bin/env python3
"""Regenerate docs/commands.md from a built kcm binary."""
import os
import pathlib
import subprocess
import sys

root = pathlib.Path(__file__).resolve().parents[1]
binary = pathlib.Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else root / "bin/kcm"
commands = ["", "profile", "context", "namespace", "contexts", "profiles", "status",
            "clear", "renew", "install", "waive", "waivers", "unwaive", "doctor",
            "init", "completion", "settings", "settings init", "settings path",
            "prompt", "exec", "version", "help"]
env = dict(os.environ, KCM_SETTINGS="~/.config/kcm/kcm_settings.toml")
sections = ["# Command help\n\nGenerated by `python3 scripts/update-help.py` from the CLI.\n"]
for command in commands:
    output = subprocess.check_output([str(binary), *command.split(), "--help"], env=env, text=True)
    sections.append("## `kcm" + (" " + command if command else "") + "`\n\n```text\n" + output.rstrip() + "\n```\n")
(root / "docs/commands.md").write_text("\n".join(sections))
